<?php

namespace App\Support;

class ServiceContentDefaults
{
    public static function all(): array
    {
        return [
            [
                'slug' => 'obstetrics',
                'title' => 'Obstetrics',
                'eyebrow' => 'Services',
                'intro' => 'Safe and structured support from early pregnancy through post-partum care.',
                'card_description' => 'Comprehensive pregnancy care, antenatal check-ups, and delivery planning with a gentle, evidence-based approach.',
                'card_icon' => 'assets/services/obstetrics-icon.png',
                'card_image' => 'assets/highlights/obstetrics.png',
                'hero_image' => 'assets/service-hero/obstetrics-hero.jpg',
                'highlight_image' => 'assets/highlights/obstetrics-latest.jpg',
                'overview_title' => 'Pre-Pregnancy',
                'overview_items' => ['Pre-conception health optimisation', 'Pre-pregnancy counselling', 'Laboratory and ultrasound check'],
                'show_intro' => false,
                'sort_order' => 10,
                'is_featured' => true,
                'service_sections' => [
                    ['title' => 'Early Pregnancy Care', 'list_items' => ['Early pregnancy scan and viability assessment', 'Management of early pregnancy complaints (e.g. nausea, vomiting, bleeding)', 'Management of early pregnancy complication (e.g. bleeding, ectopic pregnancy, recurrent miscarriage)'], 'sort_order' => 10],
                    ['title' => 'Antenatal Care', 'list_items' => ['1st trimester antenatal check-up and dating scan', 'First trimester screening', 'Management of first trimester pregnancy complaints and complication', 'Detailed scan and 2nd trimester pregnancy assessment', 'Screening and management of gestational diabetes and preeclampsia', 'Plan on delivery mode and 3rd trimester pregnancy', 'Screening and management preeclampsia and other complications in late pregnancy', 'Vaccinations during pregnancy', 'Nutritional and lifestyle guidance'], 'sort_order' => 20],
                    ['title' => 'Labour & Delivery Planning', 'list_items' => ['Vaginal birth, assisted delivery, and caesarean section counseling', 'The mode of delivery may differ pending individual maternal and pregnancy factors. This may be a vaginal delivery, an assisted vaginal delivery or caesarean section.', 'Anaesthesia and paediatric team for safe delivery'], 'sort_order' => 30],
                    ['title' => 'Postpartum Care', 'list_items' => ['Physical recovery assessment and wound care', 'Breastfeeding support and lactation counselling', 'Postnatal treatment and contraception', 'Emotional wellbeing and post-partum depression screening', 'Optimal recovery postpartum management'], 'sort_order' => 40],
                ],
            ],
            [
                'slug' => 'gynaecology',
                'title' => 'Gynaecology',
                'eyebrow' => 'Services',
                'intro' => 'Assessment, diagnosis, and treatment planning for common and complex gynecologic concerns.',
                'card_description' => 'Assessment and treatment for women\'s health concerns, from routine reviews to more complex gynecologic conditions.',
                'card_icon' => 'assets/services/gynaecology-icon.png',
                'card_image' => 'assets/highlights/gynecology.png',
                'hero_image' => 'assets/service-hero/gynaecology-hero.jpg',
                'highlight_image' => 'assets/highlights/gynaecology-latest.jpg',
                'overview_title' => 'Assessment and treatment of',
                'overview_items' => ['Abnormal menstrual cycles such irregular cycles, prolonged menses, heavy menstrual bleeding, anaemia', 'Menstrual and acute / chronic pelvic pain', 'Infertility screening', 'Vaginal discharge', 'Menopausal check up', 'Contraception and family planning', 'Cervical cancer screening: PAP smear and high risk HPV test', 'Vaccinations: Cervical cancer HPV vaccine', 'Ultrasound Pelvis, STI screening'],
                'show_intro' => false,
                'sort_order' => 20,
                'is_featured' => true,
                'service_sections' => [
                    ['title' => 'Gynecological conditions such as:', 'list_items' => ['Myoma / fibroids', 'Adenomyosis', 'Endometriosis cyst', 'Ovarian cyst', 'Endometrial polyps', 'Endometrial hyperplasia', 'Cervical polyps', 'Abnormal pap smears', 'Polycystic Ovarian Syndrome'], 'split_columns' => true, 'sort_order' => 10],
                ],
            ],
            [
                'slug' => 'minimally-invasive-surgery',
                'title' => 'Minimally Invasive Surgery',
                'eyebrow' => 'Services',
                'intro' => 'At NHScope, we specialise in minimally invasive surgical techniques, or known as LAPAROSCOPY that allow for painless surgery, minimal wound, faster recovery, better outcome using laparoscopy or robotic laparoscopy approaches.',
                'card_description' => 'Advanced laparoscopic procedures designed for precision, smaller incisions, and a more comfortable recovery.',
                'card_icon' => 'assets/services/minimally-invasive-surgery-icon.png',
                'card_image' => 'assets/highlights/minimally-invasive-surgery.png',
                'hero_image' => 'assets/service-hero/minimally-invasive-surgery-hero.png',
                'highlight_image' => 'assets/highlights/minimally-invasive-surgery-latest.png',
                'hero_suffix' => ' / PAINLESS',
                'hero_body' => 'At NHScope, we specialise in minimally invasive surgical techniques, or known as LAPAROSCOPY that allow for painless surgery, minimal wound, faster recovery, better outcome using laparoscopy or robotic laparoscopy approaches.',
                'overview_title' => 'Surgical Treatment for the Following Conditions',
                'overview_items' => ['Myoma / fibroids', 'Ovarian cyst', 'Endometriosis cyst', 'Adenomyosis', 'Chronic pelvic pain', 'Abdominal / pelvic adhesion', 'Thickened endometrium', 'Endometrial hyperplasia / precancer of the uterus', 'Abnormal menstrual bleeding (heavy, irregular, prolonged)', 'Cervical and endocervical polyps', 'Endometrial polyps', 'Ectopic pregnancy', 'Hydrosalpinx or diseased fallopian tubes', 'Cervical intraepithelial neoplasia (CIN)'],
                'overview_split_columns' => true,
                'sort_order' => 30,
                'is_featured' => true,
                'service_sections' => [
                    ['title' => 'Hysteroscopy (via the cervix, no abdominal incision)', 'list_items' => ['Polypectomy', 'Myomectomy', 'Diagnostic hysteroscopy', 'Dilatation and curettage (D&C)', 'Adhesiolysis for intrauterine adhesions (Asherman syndrome)', 'Retained IUD (intrauterine device)'], 'sort_order' => 10],
                ],
            ],
            [
                'slug' => 'laparoscopy',
                'title' => 'Laparoscopy',
                'eyebrow' => 'Procedure',
                'intro' => 'Laparoscopy or "keyhole surgery" is a modern minimally invasive technique used to diagnose and perform surgical procedures through small incisions.',
                'card_image' => 'assets/highlights/laparoscopy.png',
                'hero_image' => 'assets/service-hero/laparoscopy-hero.png',
                'highlight_image' => 'assets/highlights/laparoscopy-latest.png',
                'custom_layout' => 'laparoscopy',
                'show_intro' => false,
                'hero_body' => 'Laparoscopy, or "keyhole surgery," is a modern, minimally invasive technique used to diagnose and treat pelvic conditions through 0.5-1 cm incisions. By utilizing a laparoscope - a thin, illuminated tube with a camera - surgeons can view real-time, high-resolution images on a monitor. Compared to traditional open surgery, this approach results in less postoperative pain, smaller scars, and a faster recovery.',
                'overview_title' => 'Key Aspects of Laparoscopy:',
                'overview_items' => ['<strong>Procedure:</strong> Small incisions, typically near the belly button, and inserts a camera and specialized tools.', '<strong>Visualization:</strong> High definition view.', '<strong>Applications:</strong> Commonly used for gynecological problem (myoma / fibroid, adenomyosis, endometriosis, ovarian cysts).', '<strong>Benefits:</strong> Compared to conventional open surgery (laparotomy), this method minimize blood loss, postoperative pain - painless surgery, faster recovery and shortened hospital stay duration.', '<strong>Recovery:</strong> Most patients can return to normal activities sooner than with traditional, larger-incision surgery.'],
                'gallery_images' => ['assets/services/laparoscopy-illustration-1.png', 'assets/services/laparoscopy-illustration-2.png'],
                'sort_order' => 40,
                'service_sections' => [
                    ['title' => 'Advantages of laparoscopy surgery including:', 'list_items' => ['Minimal skin incision', 'Minimal pain', 'Precision, accuracy', 'Less bleeding', 'Reduced incidence of anemia and need for blood transfusions during and after surgery', 'Less healthy tissue damage', 'Less complications', 'Faster recovery time', 'Shortens hospitalization time', 'Less post-operative scarring', 'Better aesthetic results. With laparoscopy, the surgeon usually only requires small incisions - 0.5 only to insert laparoscopy instruments. This small incision ensures that the patient does not feel as much pain during the operation and afterward, so less analgesia (pain medication) is required.', 'Reduced unwanted side effects of analgesia.', 'The risk of infection during laparoscopy is minimal because internal organs are not exposed much to the external environment.'], 'split_columns' => true, 'sort_order' => 10],
                    ['title' => 'Common Gynecologic Conditions Treated', 'list_items' => ['Endometriosis diagnosis and ablation', 'Ovarian cyst removal (cystectomy)', 'Fibroid removal (myomectomy)', 'Hysterectomy (removal of the uterus)', 'Ectopic pregnancy treatment', 'Tubal ligation (sterilization)', 'Evaluation of pelvic pain or infertility'], 'sort_order' => 20],
                ],
            ],
            [
                'slug' => 'myoma',
                'title' => 'Myoma',
                'eyebrow' => 'Condition',
                'intro' => 'Myoma or uterine fibroids is a benign condition in which smooth muscle cells proliferate in the uterus. Uterine myomas are classified as benign tumors because they rarely transform into cancerous cells or tissues. Usually, they grow slowly over time and may not cause symptoms. However, when fibroids enlarge or become multiple, they can lead to heavy menstrual bleeding, pelvic pressure, pain, and reproductive concerns.',
                'card_image' => 'assets/highlights/myoma.png',
                'hero_image' => 'assets/service-hero/myoma-hero.jpg',
                'highlight_image' => 'assets/highlights/myoma-latest.jpg',
                'custom_layout' => 'myoma',
                'show_intro' => false,
                'hero_body' => 'Myoma, or uterine fibroids is a benign condition in which smooth muscle grow either inside or outside the uterus. Uterine myomas consist of muscle and fibrous tissue. Uterine myomas are classified as benign tumors, with vary race chance of become cancer. The size of these benign tumors can vary, ranging from as small as a marble to as large as a tennis ball, or even bigger as term pregnancy.',
                'feature_copy' => ['<strong>Myoma, or uterine fibroids is a benign condition in which smooth muscle grow either inside or outside the uterus.</strong> Uterine myomas consist of muscle and fibrous tissue. Uterine myomas are classified as benign tumors, with vary race chance of become cancer. The size of these benign tumors can vary, ranging from as small as a marble to as large as a tennis ball, or even bigger as term pregnancy.'],
                'gallery_images' => ['assets/services/myoma-illustration-1.png', 'assets/services/myoma-illustration-2.png', 'assets/services/myoma-illustration-3.png'],
                'sort_order' => 50,
                'service_sections' => [
                    ['title' => 'Causes of Uterine Myomas', 'copy' => 'The exact cause of uterine myomas remains unknown to this day. However, several factors are believed to increase a person\'s risk of developing fibroids, including : A family history of uterine myomas, having the first menstrual cycle at a young age, specifically under the age of 12, obesity or being overweight, reproductive hormone imbalances, particularly involving estrogen and progesterone. Unfortunately, any women may be unaware of this condition, as uterine myomas often do not cause specific symptoms. In fact, most cases are discovered incidentally during an ultrasound (USG).', 'sort_order' => 10],
                    ['title' => 'Symptoms of Uterine Myomas', 'copy' => 'Uterine myomas often do not trigger specific symptoms, making it difficult for individuals to recognize the condition. Regardless, some common uterine fibroid symptoms include : Menstrual pain, heavy menses, prolonged menses, pelvic pain, abdominal bloating or a feeling of fullness, frequent urination, which may occur if the myoma presses against the bladder, constipation, which may occur if the myoma presses against the large intestine.', 'sort_order' => 20],
                    ['title' => 'How to diagnose uterine myomas?', 'copy' => 'Several diagnostic procedures can be performed by a doctor to confirm the presence of uterine myomas, including patients\' complaints and a family history, physical examination, ultrasound (USG), Magnetic Resonance Imaging (MRI), hysteroscopy. A procedure where a thin, flexible tube equipped with a camera is inserted through the vagina to examine the inside of the uterus.', 'sort_order' => 30],
                    ['title' => 'Treatments for Uterine Myomas', 'copy' => 'Several diagnostic procedures can be performed by a doctor to confirm the presence of uterine myomas, including : patient\'s symptoms and family history, physical examination, ultrasound (USG), Magnetic Resonance Imaging (MRI), hysteroscopy. A procedure where a thin, flexible tube equipped with a camera is inserted through the vagina to examine the inside of the uterus.', 'sort_order' => 40],
                    ['title' => 'Surgery for myoma', 'copy' => 'The option for surgery must be discussed properly, to know what is the patient need and choices of surgery. The choice as follows :', 'list_items' => ['Myomectomy, a surgical procedure to remove uterine myomas is usually recommended for patients with large myomas or for younger women who are planning to get pregnant.', 'Hysterectomy, a surgical procedure to remove the uterus. This is generally performed on patients who are no longer in their reproductive years and are experiencing symptoms that interfere with daily activities.', 'Robotic surgery, a minimally invasive technique that uses the robotic system to treat complex cases in a difficult-to-reach area.'], 'sort_order' => 50],
                ],
            ],
            [
                'slug' => 'endometriosis',
                'title' => 'Endometriosis',
                'eyebrow' => 'Condition',
                'intro' => 'Endometriosis is a disease where tissue similar to the lining of the uterus grows outside the uterus. This can cause pelvic pain, especially during menstrual periods, and it may also affect fertility. The exact cause of endometriosis is not fully understood, but genetics, immune system dysfunction, and retrograde menstruation are thought to play a role.',
                'card_image' => 'assets/highlights/endometriosis.png',
                'hero_image' => 'assets/service-hero/endometriosis-hero.jpg',
                'highlight_image' => 'assets/highlights/endometriosis-latest.jpg',
                'custom_layout' => 'endometriosis',
                'show_intro' => false,
                'hero_body' => 'Endometriosis is a disease condition in which tissue that is similar to the inner lining of the uterus grows outside the uterus. It often affects the ovaries, fallopian tubes and the tissue lining the pelvis, on the outside surface of the uterus, or the tissues surrounding the uterus and the ovaries. Rarely, endometriosis growths may be found beyond the area where pelvic organs are located.',
                'feature_copy' => ['<strong>Endometriosis tissue acts as the lining inside the uterus would - it thickens, breaks down and bleeds with each menstrual cycle.</strong> But it grows in places where it doesn\'t belong, and it doesn\'t leave the body. When endometriosis involves the ovaries, cysts called endometriomas may form. Surrounding tissue can become irritated and form scar tissue. Bands of fibrous tissue called adhesions also may form. These can cause pelvic tissues and organs to stick to each other.Other form is the adenomyosis, in which the uterus muscular layer is thickened because of endometriosis cell within the myometrium.'],
                'feature_image' => 'assets/services/endometriosis-illustration.png',
                'sort_order' => 60,
                'service_sections' => [
                    ['title' => 'Symptoms', 'copy' => 'The main symptom of endometriosis is pelvic pain. Symptoms vary widely between individuals. Some have no symptoms, while for others it can be a debilitating disease. It\'s often linked with menstrual periods. Although many people have cramping during their periods, those with endometriosis often describe menstrual pain that\'s far worse than usual. The pain also may become worse over time.<br><br><strong>Common symptoms of endometriosis include:</strong>', 'list_items' => ['Menstrual pain. Pelvic pain and cramping may start before a menstrual period and last for days into it. You also may have lower back and stomach pain. Another name for painful periods is dysmenorrhea.', 'Heavy menses. Sometimes, you may have heavy menstrual periods or bleeding between periods.', 'Pelvic pain. Uncomfortable lower abdomen / back pain during or outside the menstrual period.', 'Infertility. For some people, endometriosis is first found during tests for infertility treatment.', 'Pain with sex. Pain during or after sex is common with endometriosis.', 'Pain with bowel movements or urination. You\'re most likely to have these symptoms before or during a menstrual period.'], 'sort_order' => 10],
                    ['title' => '', 'copy' => 'A presumed diagnosis can be made based on symptoms and medical imaging; a laparoscopy (keyhole surgery) with a biopsy can provide definite confirmation. Other causes of similar symptoms include adenomyosis, uterine fibroids, irritable bowel syndrome, and interstitial cystitis.<br><br>While there is no cure for endometriosis, several treatments may improve symptoms. This includes pain medication, hormonal treatments or surgery. The recommended pain medication is usually a non-steroidal anti-inflammatory drug (NSAID), such as mefenamic acid or naproxen. Taking the birth control pill continuously or using a hormonal coil (coil) is another first-line treatment. Other types of hormonal treatment can be tried if the pill or IUD are not effective. Endometriosis can be removed surgically in women whose symptoms are not relieved by other treatments or to help with infertility.', 'sort_order' => 20],
                    ['title' => 'Surgery', 'copy' => 'Laparoscopy the uterus and fallopian tubes. The abdomen is filled with gas so that the surgeon can see better and have space for instruments.<br><br>Clinical guidelines recommend surgery when medical treatment does not work sufficiently, has unacceptable side effects or is contraindicated. Large endometriomas can only effectively be treated with surgery. Surgery is also recommended when deep endometriosis causes problems in the bowels or bladder, such as obstruction. It is unclear what the effect of surgery is for pain relief in cases of superficial peritoneal endometriosis.<br><br><strong>Laparoscopy (keyhole surgery) is the standard surgical approach. Treatment consists of the removal of endometriosis and the restoration of pelvic anatomy via the division of adhesions.</strong><br><br>With laparoscopic surgery, small instruments are inserted through incisions to remove the endometriosis tissue and adhesions. After surgery, people can usually return home the same day.<br><br>Endometriomas are usually excised (removed completely). Compared to drainage and coagulation of the cyst, excision makes it less likely the cysts and pain symptoms come back. For deep endometriosis, surgery improves quality of life and pain symptoms. However, the procedure can be complicated, especially if the lesions are in or near the bowel, ureter of the urinary system or the chest, and requires a interdisciplinary surgical team in those cases. For instance, for rectovaginal endometriosis, 7% of surgeries had complications. Sometimes, a part of the bowel or bladder is removed. For women who still have significant pain after hormonal treatment and other surgery, and do not want to become pregnant, a hysterectomy (removal of the womb) can be offered. This is done in combination with removal of endometriosis lesions. Removal of the womb may be beneficial if the uterus itself is affected by adenomyosis.', 'sort_order' => 30],
                    ['title' => 'When to see a doctor', 'copy' => 'See a member of your health care team if you think you might have symptoms of endometriosis.<br><br><strong>Endometriosis can be a challenge to manage. You may be better able to take charge of the symptoms if:</strong>', 'list_items' => ['Your care team finds the disease sooner rather than later.', 'You learn as much as you can about endometriosis.', 'You get treatment from a team of health care professionals from different medical fields if needed.'], 'sort_order' => 40],
                ],
            ],
            [
                'slug' => 'ovarian-cyst',
                'title' => 'Ovarian Cyst',
                'eyebrow' => 'Condition',
                'intro' => 'Ovarian cysts are fluid-filled sacs that can form on the ovary and may require monitoring or treatment depending on size and symptoms. Many are benign and may resolve spontaneously, while others may persist, enlarge, or cause pain, torsion, or bleeding and need surgical management.',
                'card_image' => 'assets/highlights/ovarian-cyst.png',
                'hero_image' => 'assets/service-hero/ovarian-cyst-hero.jpg',
                'highlight_image' => 'assets/highlights/ovarian-cyst-latest.jpg',
                'custom_layout' => 'ovarian-cyst',
                'show_intro' => false,
                'hero_body' => 'Ovarian cysts are fluid-filled sacs within or on the surface of an ovary. They vary in size and content, and may be benign or malignant. Symptomatic ovarian cyst may cause pelvic pain, bloating, or fullness. Treatment, if needed, often involves monitoring, hormonal birth control to prevent new ones, or surgery for large/painful cases.',
                'overview_title' => 'Key Aspects of Ovarian Cysts',
                'overview_items' => ['<strong>Main Causes:</strong> The majority are functional cyst, caused by the menstrual cycle, where a follicle either fails to release an egg or doesn\'t shrink after releasing one. Other types include endometriosis, dermoid cyst and benign cystadenoma.', '<strong>Symptoms:</strong> The majority of ovarian cysts are asymptomatic. Larger ovarian cysts may twist or rupture, resulting in acute abdominal pain, nausea and vomiting. Patients with endometriotic cysts may present with painful menses (dysmenorrhoea) and intercourse (dyspareunia).', '<strong>Other symptoms include:</strong>', 'menstrual irregularities', 'bloatedness', 'lower abdominal discomfort', 'loss of appetite or weight', 'passing urine more frequently or change in bowel habit (constipation or diarrhoea) due to compression from the cyst', 'As ovarian cancer tends to develop insidiously with vague symptoms, the above symptoms should not be ignored, especially if they are new or experienced on a frequent basis.', '<strong>Treatment:</strong> Small, functional cysts often disappear without treatment within 1-3 months. Treatment for symptomatic or persistent cysts may include pain management or surgical removal.', '<strong>Diagnosis:</strong> Diagnosis of Ovarian Cysts'],
                'feature_images' => ['assets/services/ovarian-cyst-illustration-1.png', 'assets/services/ovarian-cyst-illustration-2.png'],
                'gallery_images' => ['assets/services/ovarian-cyst-photo-1.png', 'assets/services/ovarian-cyst-photo-2.png', 'assets/services/ovarian-cyst-photo-3.png'],
                'sort_order' => 70,
                'service_sections' => [
                    ['title' => 'How are ovarian cysts diagnosed?', 'copy' => 'Ultrasound is the preferred method for characterising ovarian cysts. Features such as solid areas, multiple internal compartments, irregular margins and high velocity blood flow increase the index of suspicion for ovarian cancer. A blood test for CA125 may be taken if there is concern about malignancy. This blood protein is frequently raised in ovarian cancer, but must be interpreted in conjunction with symptoms and ultrasound findings as it can also be raised in non-cancerous conditions such as endometriosis and fibroids.', 'sort_order' => 10],
                    ['title' => 'Treatment for Ovarian Cysts', 'list_items' => ['Management depends on your symptoms, characteristics of the cyst and results of blood tests. Small asymptomatic ovarian cysts that have no suspicious features on ultrasound may be managed expectantly. This usually involves a follow-up ultrasound scan in about three to four months to monitor for any change in size or appearance of the cyst. Surgery will be recommended if the ovarian cyst is symptomatic or has abnormal features.', '<strong>Laparoscopy (keyhole surgery)</strong> is the approach of choice if the risk of malignancy is low, as it is associated with less post-operative pain and a faster recovery. LAPAROSCOPY IS THE BEST WAY TO TREAT OVARIAN CYST, ENDOMETRIOSIS, DERMOID CYST. Laparoscopy offers painless surgery, less bleeding, less complication, faster recovery and less hospital stay.', '<strong>Laparotomy (open surgery)</strong> may be recommended if you have had previous surgery, if the ovarian cyst is large or if it has suspicious features.', '<strong>Cystectomy</strong> involves the removal of the cyst with preservation of normal ovarian tissue. This is usually done for pre-menopausal women in order to conserve ovarian tissue for reproductive and hormonal function.', '<strong>Oophorectomy</strong> is the surgical procedure to remove the entire ovary. Post-menopausal women will usually be offered removal of both ovaries as this has the advantage of reducing the risk of developing ovarian cancer or cysts in the future.', 'If the risk of ovarian cancer is high, your doctor will discuss frozen section and surgical staging.', '<strong>Frozen section</strong> involves sending the excised ovarian tissue for microscopic examination while you are still under general anaesthesia. If this test reveals malignant cells and you have given prior consent, your surgeon may then proceed to perform a full staging surgery as part of the treatment for ovarian cancer. This involves removing the uterus, both fallopian tubes and ovaries, the omentum (a layer of fatty tissue that covers the abdominal contents like an apron) as well as lymph nodes.'], 'sort_order' => 20],
                ],
            ],
            [
                'slug' => 'hysterectomy',
                'title' => 'Hysterectomy',
                'eyebrow' => 'Procedure',
                'intro' => 'A hysterectomy is a common major surgical procedure that involves the removal of the uterus (womb), which stops menstruation and prevents pregnancy. It is used to treat conditions like uterine fibroids, endometriosis, chronic pain, pelvic prolapse, and gynecologic cancers. It may also involve removing the cervix, ovaries, or fallopian tubes.',
                'card_image' => 'assets/highlights/hysterectomy.png',
                'hero_image' => 'assets/service-hero/hysterectomy-hero.jpg',
                'highlight_image' => 'assets/highlights/hysterectomy-latest.jpg',
                'custom_layout' => 'hysterectomy',
                'show_intro' => false,
                'hero_body' => 'A hysterectomy is a common major surgical procedure that involves the removal of the uterus (womb), which stops menstruation and prevents pregnancy. It is used to treat conditions like uterine fibroids, endometriosis, chronic pain, pelvic prolapse, and gynecologic cancers. It may also involve removing the cervix, ovaries, or fallopian tubes.',
                'overview_title' => 'Key Aspects of Hysterectomy:',
                'overview_items' => ['<strong>Types:</strong> A total hysterectomy removes the uterus and cervix, while a subtotal/supracervical hysterectomy removes only the uterus, leaving the cervix.', '<strong>At National Hospital,</strong> most of the procedure is done by laparoscopy. Laparoscopy offers you better outcome, since laparoscopy is using small incision, which leads to minimal pain / painless. Small scar means faster recovery, faster healing. Laparoscopy is also using high-definiton laparoscope camera, to enhance the accuracy. Hence, laparoscopy is the most used procedure to do hysterectomy.', '<strong>Approaches:</strong> Procedures can be done abdominally (open), vaginally, or laparoscopically (minimally invasive).', '<strong>Ovaries:</strong> Removal of the ovaries (oophorectomy) may occur at the same time, which causes immediate menopause if not already reached.', '<strong>Recovery:</strong> Full recovery usually takes about 2 to 4 weeks, during which heavy lifting and sexual activity should be avoided.', '<strong>Alternatives:</strong> Depending on the condition, options like medication, ablation, or embolization may be considered before surgery.'],
                'sort_order' => 80,
                'service_sections' => [
                    ['title' => 'Reasons for the Procedure', 'copy' => 'Fibroid / myoma, endometriosis / adenomyosis, chronic pelvic pain, gynaecology cancer, uterine prolaps', 'sort_order' => 10],
                ],
            ],
        ];
    }
}
